# -*- coding: utf-8 -*-
"""dynamicpricing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BtFkC6V-K95G336KvjTrOLxo4SjqobA
"""

import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_excel("/content/datasetdelacompe.xlsx")
df = df[~df['Precio'].isin(["Precio"])]

def palabras_mas_comunes(texto):
    palabras = texto.split()
    contador = Counter(palabras)
    return dict(contador.most_common())

frecuencia_palabras = df['Producto'].apply(palabras_mas_comunes).tolist()

resultado = {}
for diccionario in frecuencia_palabras:
    for palabra, frecuencia in diccionario.items():
        if palabra in resultado:
            resultado[palabra] += frecuencia
        else:
            resultado[palabra] = frecuencia

resultado_ordenado = dict(sorted(resultado.items(), key=lambda item: item[1], reverse=True))

print(resultado_ordenado)

df["Subcategoria"] = df["Categoria"]
def subcategorizar(x):
  for index, row in df.iterrows():
      if x in row['Producto']:
          df.at[index, 'Subcategoria'] = x
subcategorizar("Cartuchera")
subcategorizar('Aretes')
subcategorizar('Abanico')
subcategorizar('Tapiz')
subcategorizar('Mensaje')
subcategorizar('Llavero')
subcategorizar('Monedero')
subcategorizar('Chocolate')
subcategorizar('Tapíz')
subcategorizar('Cuerda')
subcategorizar('gafas')
subcategorizar('Bolsas')
subcategorizar('Pulsera')
#'Cartuchera': 140, 'Guajira': 98, 'Mochila': 91, 'Putumayo': 84,  'Wayúu': 66, 'Mampuján': 66, 'Aretes': 57, 'Abanico': 41, 'Tapiz': 40,'Mensaje': 30,
#'Llavero': 29, 26, 'Monedero': 26, 'Chocolate': 25, 'Tapíz': 24, 'Cuerda': 24, 'gafas': 24, 'Bolsas': 21, 'Pulsera': 20

df.to_excel('prueba.xlsx', index=False)
df

"""# Nueva sección"""

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_excel("/content/dataframelim.xlsx")

fig = px.box(df, x="Subcategoria", y="Precio", points = "outliers", color = "Empresa")
fig.show()
category_counts = df['Categoria'].value_counts()

grouped_df = df.groupby([ 'Subcategoria', 'Empresa']).size().unstack(fill_value=0)

# Crear gráfico de barras agrupados para mostrar la distribución de productos por categoría y subcategoría
grouped_df.plot(kind='bar', stacked=True, figsize=(10, 6))
plt.title('Distribución de cantidad de productos con respecto a las empresas')
plt.xlabel('Categoría y Subcategoría')
plt.ylabel('Cantidad de productos')
plt.xticks(rotation=45)
plt.legend(title='Empresa')
plt.show()

"""# Nueva sección"""

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_excel("/content/compaprecios.xlsx")

plt.figure(figsize=(8, 6))
for category, group in df.groupby('Subcategoria'):
    plt.scatter(group['Precio de venta'], group['Utilidad Bruta $'], label=category)
plt.title('Gráfico de dispersión de Utilidad Bruta vs Precio de Venta con la categoría')
plt.xlabel('Precio de Venta')
plt.ylabel('Utilidad Bruta $')
plt.legend()
plt.grid(True)
plt.show()


plt.figure(figsize=(8, 6))
for category, group in df.groupby('Subcategoria'):
    plt.scatter(group['Precio de venta'], group['Margen Bruto%'], label=category)
plt.title('Gráfico de dispersión de Margen Bruto vs Precio de Venta con la categoría')
plt.xlabel('Precio de Venta')
plt.ylabel('Margen Bruto%')
plt.legend()
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("C:\Users\valentina\Downloads\compaprecios.xlsx")

correlation_matrix = df[['Precio de venta', 'Costo unitario', 'Utilidad Bruta $', 'Margen Bruto%']].corr()


plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Matriz de correlación')
plt.show()